name: build-frontend

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish head Docker image
      uses: VaultVulp/gp-docker-action@1.2.0
      with:
        image-name: gestion-de-proyectos-front
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy package to aws
      uses: appleboy/ssh-action@master
      env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.OMAR_SSH_HOST }}
        username: ${{ secrets.OMAR_SSH_USER }}
        key: ${{ secrets.OMAR_SSH_KEY }}
        port: 22
        envs: GITHUB_USERNAME, GITHUB_TOKEN, OMAR_SSH_KEY
        script: |
          docker stop gestion-de-proyectos-front
          docker container rm gestion-de-proyectos-front
          docker login ghcr.io -u Omar-Lamprea -p $GITHUB_TOKEN
          docker pull ghcr.io/omar-lamprea/gestion-de-proyectos/gestion-de-proyectos-front:latest
          docker run -d --restart unless-stopped -p 8080:8080 --name "gestion-de-proyectos-front" -e NODE_ENV=production ghcr.io/omar-lamprea/gestion-de-proyectos-front/gestion-de-proyectos-front:latest
